name: Lint

on: [push]

jobs:
  files:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    strategy:
      matrix:
        package: ["strategies-keep3r", "stealth-txs"]
    steps:
      - name: Check out github repository
        id: github-checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v11

      - name: Cache node modules
        id: cache-node-modules
        uses: actions/cache@v2
        if: contains(steps.changed-files.outputs.all_changed_and_modified_files, matrix.package)
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install node
        id: install-node
        uses: actions/setup-node@v1
        if: contains(steps.changed-files.outputs.all_changed_and_modified_files, matrix.package)
        with:
          node-version: "12.x"

      - name: Install dependencies
        id: install-dependencies
        if: contains(steps.changed-files.outputs.all_changed_and_modified_files, matrix.package)
        run: lerna bootstrap

      - name: Run linter
        if: contains(steps.changed-files.outputs.all_changed_and_modified_files, matrix.package)
        run: lerna exec --ignore @yearn/commons -- yarn compile && lerna exec --scope @yearn/${{ matrix.package }}  -- yarn run lint:check

  commits:
    runs-on: ubuntu-latest

    steps:
      - name: Check out github repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Run commitlint
        uses: wagoid/commitlint-github-action@v2